### ISSUE TITLE
Main Menu and scene switching

### ISSUE THREAD

**Issue by TurboMair** [TurboMair/nwmsusoftprac#7]
The main menu should look polished with a map of the US, buttons to enter each level, and some method to show the players level progress. The coding to properly switch scenes into the levels will also be handled here. There are many other optimizations that could be added, such as an customization tab to change the players name and look, however the scene switching takes priority

**Comment by haebin827** [comment]
**Here's some updates:**

1. Added appropriate US map photos.
2. Added buttons according to each game difficulty level (easy, medium, hard), and designed the buttons differently for normal, hover, and pressed states.
3. Wrote GDScript and added appropriate signals to each button so that it changes to the corresponding game scene when the user presses a button.
4. Designed the progress bar and added it to the scene
